spring.application.name=Smart_Contact_Manager
#Change Server port here
server.port=8081

spring.output.ansi.enabled=ALWAYS

#MySQL Database Configuration
#data source url
spring.datasource.url=jdbc:mysql://localhost:3306/scm
spring.datasource.username=root
spring.datasource.password=root1234

#Jpa configurations
spring.jpa.properties.hibernate.show_sql=true
spring.jpa.properties.hibernate.use_sql_comments=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.hibernate.ddl-auto=update

#Email Configuration

#OAuth2 Client Configurations

#Google Configure
spring.security.oauth2.client.registration.google.client-name=Google
spring.security.oauth2.client.registration.google.client-id=1046227544365-pcc0hchp2d401uh5hfhc507kk9id4u39.apps.googleusercontent.com
spring.security.oauth2.client.registration.google.client-secret=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
spring.security.oauth2.client.registration.google.scope=email,profile

#Github Configure
spring.security.oauth2.client.registration.github.client-name=Github
spring.security.oauth2.client.registration.github.client-id=Iv23liGbRmLB8bnAMg07
spring.security.oauth2.client.registration.github.client-secret=f070fb8e5960890bca10d47cdf9db725215fbde2
spring.security.oauth2.client.registration.github.scope=email,profile